/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Child = IDL.Record({
  'age' : IDL.Nat,
  'emergency' : IDL.Bool,
  'name' : IDL.Text,
  'parentPhone' : IDL.Text,
  'chipID' : IDL.Text,
});

export const idlService = IDL.Service({
  'clearEmergency' : IDL.Func([IDL.Text], [], []),
  'getAllChildren' : IDL.Func([], [IDL.Vec(Child)], ['query']),
  'getChild' : IDL.Func([IDL.Text], [Child], ['query']),
  'registerChild' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
  'scanChip' : IDL.Func([IDL.Text], [Child], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Child = IDL.Record({
    'age' : IDL.Nat,
    'emergency' : IDL.Bool,
    'name' : IDL.Text,
    'parentPhone' : IDL.Text,
    'chipID' : IDL.Text,
  });
  
  return IDL.Service({
    'clearEmergency' : IDL.Func([IDL.Text], [], []),
    'getAllChildren' : IDL.Func([], [IDL.Vec(Child)], ['query']),
    'getChild' : IDL.Func([IDL.Text], [Child], ['query']),
    'registerChild' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
    'scanChip' : IDL.Func([IDL.Text], [Child], []),
  });
};

export const init = ({ IDL }) => { return []; };